/* KESTREL METAL - Home 页面项目数据（世界地图） */
window.KESTREL_PROJECTS = [
  { id: 0, name: 'Kestrel Metal HQ', location: 'Anping, Hebei, China', type: 'Headquarters & Manufacturing', description: 'Global headquarters and main manufacturing campus in Anping - China\'s Wire Mesh Capital', capacity: '20,000 sqm', year: 2014, coordinates: [115.26, 38.22], isHQ: true },
  { id: 1, name: 'Shanghai Distribution Center', location: 'Shanghai, China', type: 'Regional Warehouse', description: 'Eastern China distribution hub for quick order fulfillment and logistics', capacity: '5,000 sqm', year: 2017, coordinates: [121.47, 31.23] },
  { id: 2, name: 'Guangzhou Export Terminal', location: 'Guangzhou, China', type: 'Export Shipping Hub', description: 'Southern China export terminal handling container shipments worldwide', capacity: '-', year: 2018, coordinates: [113.26, 23.13] },
  { id: 3, name: 'Beijing Project Office', location: 'Beijing, China', type: 'Project Coordination', description: 'Northern China project management and engineering coordination office', capacity: '-', year: 2019, coordinates: [116.40, 39.90] },
  { id: 4, name: 'Mumbai Fencing Supply', location: 'Mumbai, India', type: 'Fencing Supply Project', description: 'Large-scale security fencing supply for industrial and infrastructure projects', capacity: '50,000m', year: 2020, coordinates: [72.87, 19.07] },
  { id: 5, name: 'Delhi Airport Perimeter', location: 'Delhi, India', type: 'Airport Security Fencing', description: 'Airport perimeter security fencing installation with 3D wire panels', capacity: '12,000m', year: 2021, coordinates: [77.21, 28.61] },
  { id: 6, name: 'Dubai Industrial Fencing', location: 'Dubai, UAE', type: 'Industrial Fencing Project', description: 'Industrial facility perimeter fencing for manufacturing and logistics zones', capacity: '30,000m', year: 2019, coordinates: [55.27, 25.20] },
  { id: 7, name: 'Saudi Arabia Security Project', location: 'Riyadh, Saudi Arabia', type: 'High-Security Fencing', description: 'High-security fencing with razor wire for critical infrastructure protection', capacity: '25,000m', year: 2020, coordinates: [46.68, 24.71] },
  { id: 8, name: 'Istanbul Manufacturing Supply', location: 'Istanbul, Turkey', type: 'Wire Mesh Supply', description: 'Supply of welded wire mesh and chain link fencing for construction projects', capacity: '40,000m', year: 2018, coordinates: [28.97, 41.01] },
  { id: 9, name: 'Germany Distribution Hub', location: 'Hamburg, Germany', type: 'European Distribution', description: 'European distribution hub serving customers across the EU region', capacity: '-', year: 2016, coordinates: [10.00, 53.55] },
  { id: 10, name: 'UK Construction Supply', location: 'London, UK', type: 'Construction Wire Mesh', description: 'Construction reinforcement mesh supply for UK building projects', capacity: '15,000 tons', year: 2019, coordinates: [-0.13, 51.51] },
  { id: 11, name: 'France Agricultural Fencing', location: 'Paris, France', type: 'Agricultural Fencing', description: 'Farm and agricultural fencing supply for livestock and crop protection', capacity: '20,000m', year: 2020, coordinates: [2.35, 48.85] },
  { id: 12, name: 'Australia Farm Fencing', location: 'Sydney, Australia', type: 'Agricultural & Farm Fencing', description: 'Large-scale farm fencing for livestock protection in Australian rural areas', capacity: '100,000m', year: 2017, coordinates: [151.21, -33.87] },
  { id: 13, name: 'New Zealand Wire Supply', location: 'Auckland, New Zealand', type: 'Wire Products Distribution', description: 'Wire products and fencing distribution across New Zealand', capacity: '-', year: 2019, coordinates: [174.76, -36.85] },
  { id: 14, name: 'Brazil Construction Project', location: 'São Paulo, Brazil', type: 'Construction Mesh Supply', description: 'Construction wire mesh supply for Brazilian infrastructure projects', capacity: '25,000 tons', year: 2020, coordinates: [-46.63, -23.55] },
  { id: 15, name: 'Argentina Agricultural Supply', location: 'Buenos Aires, Argentina', type: 'Agricultural Fencing', description: 'Agricultural and farm fencing for livestock production in Argentina', capacity: '60,000m', year: 2018, coordinates: [-58.38, -34.60] },
  { id: 16, name: 'South Africa Mining Fencing', location: 'Johannesburg, South Africa', type: 'Mining Security Fencing', description: 'Mining site security fencing with anti-climb and razor wire systems', capacity: '35,000m', year: 2019, coordinates: [28.04, -26.20] },
  { id: 17, name: 'Kenya Infrastructure', location: 'Nairobi, Kenya', type: 'Infrastructure Fencing', description: 'Infrastructure project fencing for construction and utilities', capacity: '18,000m', year: 2021, coordinates: [36.82, -1.29] },
  { id: 18, name: 'Nigeria Perimeter Security', location: 'Lagos, Nigeria', type: 'Perimeter Security Fencing', description: 'Perimeter security fencing for commercial and industrial properties', capacity: '22,000m', year: 2020, coordinates: [3.38, 6.45] },
  { id: 19, name: 'Russia Industrial Fencing', location: 'Moscow, Russia', type: 'Industrial Fencing', description: 'Industrial facility fencing and wire mesh supply for Russian market', capacity: '50,000m', year: 2017, coordinates: [37.61, 55.75] },
  { id: 20, name: 'Canada Construction Mesh', location: 'Toronto, Canada', type: 'Construction Wire Mesh', description: 'Construction wire mesh and rebar products for Canadian building projects', capacity: '20,000 tons', year: 2019, coordinates: [-79.38, 43.65] },
  { id: 21, name: 'USA Fencing Distribution', location: 'Los Angeles, USA', type: 'Fencing Distribution Center', description: 'US West Coast distribution center for fencing and wire mesh products', capacity: '-', year: 2018, coordinates: [-118.24, 34.05] },
  { id: 22, name: 'Mexico Agricultural Supply', location: 'Mexico City, Mexico', type: 'Agricultural Fencing', description: 'Agricultural and livestock fencing supply for Mexican farms', capacity: '45,000m', year: 2021, coordinates: [-99.13, 19.43] }
];

/* KESTREL METAL - ProjectManagement tab 内容 */
window.KESTREL_PM_ICONS = {
  consultation: '<svg width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path></svg>',
  design: '<svg width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline></svg>',
  production: '<svg width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"></path></svg>',
  quality: '<svg width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg>',
  logistics: '<svg width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="1" y="3" width="15" height="13"></rect><polygon points="16 8 20 8 23 11 23 16 16 16 16 8"></polygon><circle cx="5.5" cy="18.5" r="2.5"></circle><circle cx="18.5" cy="18.5" r="2.5"></circle></svg>',
  support: '<svg width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 18v-6a9 9 0 0 1 18 0v6"></path><path d="M21 19a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3zM3 19a2 2 0 0 0 2 2h1a2 2 0 0 0 2-2v-3a2 2 0 0 0-2-2H3z"></path></svg>'
};
